lane:
    smoothing: 0.05
    num_interpolated: 200
    waypoints: # [<East (m)>, <North (m)>]
        - [ 0.00,  0.00]
        - [ 0.00,  5.00]
        - [ 3.00,  9.00]
        - [ 7.00,  9.00]
        - [ 7.00,  4.00]
        - [ 4.00,  4.00]
        - [ 4.00,  0.00]
        - [-2.00, -4.00]

ego_motion:
    smoothing: 0.05
    smoothing_yaw_deviation: 1.0e-5
    num_interpolated: 200
    waypoints: # [<Time (s)>, <East (m)>, <North (m)>, <Yaw deviation (rad)>]
        - [ 0.0,  0.50,  0.50,  0.025]
        - [12.0, -0.40,  5.00,  0.015]
        - [22.0,  3.00,  8.60,  0.025]
        - [26.0,  6.50,  9.30, -0.010]
        - [38.0,  6.60,  4.00, -0.020]
        - [42.0,  4.30,  3.60, -0.025]
        - [46.0,  3.85,  0.30,  0.005]
        - [54.0,  2.00, -5.30,  0.010]

measurement_noise_camera:
    expected_number_of_measurements: 10
    radial:
        degrees_of_freedom: 2
        scaling: 0.05

measurement_noise_imu:
    velocity_variance: 0.1
    angular_velocity_variance: 0.1

camera:
    frame_width: 2.0
    frame_height: 3.0
